### PR TITLE
Fix ACPI "Open All" issue on non English interfaces

### PR DESCRIPTION
**Pull request by williambj1**
@vit9696 @usr-sse2 @Moorre @PMheart 

Hi!
This is a solution for https://github.com/acidanthera/bugtracker/issues/313

First of all, I have to apologize that I'm an idiot in Objective-C. 
This solution is not efficient at all.
There may be other solutions like using button tags or ids but I failed to make it work.

If this is too redundant and there is an alternative solution, please close this PR.

Thank you very much!

### CODE REVIEW

**Comment by vit9696** [comment]
@williambj1, thanks for tracking down the issue as well as the patch. I have a better idea how to fix this, and it will be nice if you could implement it. Let me explain.

In Objective-C we have localised strings, which are stored in dedicated files named `Localizable.strings`. If you create new entries for all the three items in each locale (`Cancel`, `Open Selected`, `Open All`), you could then use `NSLocalizedString(@"tag", @"comment");` to obtain the value for the current localisation in Objective-C code.

The idea is pretty much the same to [this fix](https://github.com/acidanthera/MaciASL/commit/1fe3a3a494f3f659cfc4ef1f77699fdbe0c661c5#diff-1695a7ebcbeb253c87d331e7e1fff473R195
). The example file can be found [here](https://github.com/acidanthera/MaciASL/blob/1fe3a3a494f3f659cfc4ef1f77699fdbe0c661c5/MaciASL/en.lproj/Localizable.strings). This way the code in .m file will be the same for all localisations.

**Comment by williambj1** [comment]
Thanks! I'll try that a few hours later.😀

**Comment by williambj1** [comment]
@vit9696 
Fixed! Please have a look!

Thanks!

**Comment by vit9696** [comment]
Makes sense to me, merged & thanks.

**Pull request merged**
