### PR TITLE
Small Improvements for the Chinese Translation

### PR DESCRIPTION
**Pull request by williambj1**
Hi @vit9696 @PMheart 
After using the Chinese Version for one week, I discovered that some terms need to be improved, so I made this PR.

### CODE REVIEW

**Comment by PMheart** [comment]
Thanks a lot!

**Comment by btwise** [comment]
这个版本的MACIASL在我的10.14.4系统上编译后运行，无法出现主界面，只有菜单栏可以显示，是什么问题？

2019-03-09 10:51:10.702593+0800 MaciASL[1753:21804] -[__NSCFConstantString background]: unrecognized selector sent to instance 0x1000548f0
2019-03-09 10:51:10.702810+0800 MaciASL[1753:21804] -[__NSCFConstantString background]: unrecognized selector sent to instance 0x1000548f0
2019-03-09 10:51:10.788743+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C14.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:10.788919+0800 MaciASL[1753:21837] TIC Read Status [14:0x600003720cc0]: 1:54
2019-03-09 10:51:10.789891+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C13.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:10.790132+0800 MaciASL[1753:21837] TIC Read Status [13:0x600003718f00]: 1:54
2019-03-09 10:51:10.790849+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C15.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:10.791441+0800 MaciASL[1753:21837] TIC Read Status [15:0x600003721e00]: 1:54
2019-03-09 10:51:10.792300+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C16.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:10.792417+0800 MaciASL[1753:21837] TIC Read Status [16:0x600003722280]: 1:54
2019-03-09 10:51:11.089584+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C18.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.089892+0800 MaciASL[1753:21837] TIC Read Status [18:0x60000371c300]: 1:54
2019-03-09 10:51:11.090581+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C20.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.090747+0800 MaciASL[1753:21837] TIC Read Status [20:0x60000372dec0]: 1:54
2019-03-09 10:51:11.091189+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C1.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.091272+0800 MaciASL[1753:21837] TIC Read Status [1:0x6000037149c0]: 1:54
2019-03-09 10:51:11.091830+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C17.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.091930+0800 MaciASL[1753:21837] TIC Read Status [17:0x60000372d740]: 1:54
2019-03-09 10:51:11.092331+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C19.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.092431+0800 MaciASL[1753:21837] TIC Read Status [19:0x600003728780]: 1:54
2019-03-09 10:51:11.419869+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C24.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.420051+0800 MaciASL[1753:21837] TIC Read Status [24:0x60000372df80]: 1:54
2019-03-09 10:51:11.424269+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C28.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.424542+0800 MaciASL[1753:21837] TIC Read Status [28:0x600003728cc0]: 1:54
2019-03-09 10:51:11.425114+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C26.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.425237+0800 MaciASL[1753:21837] TIC Read Status [26:0x60000372a880]: 1:54
2019-03-09 10:51:11.670244+0800 MaciASL[1753:21837] [] nw_socket_handle_socket_event [C31.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.670544+0800 MaciASL[1753:21837] TIC Read Status [31:0x6000037298c0]: 1:54
2019-03-09 10:51:11.672059+0800 MaciASL[1753:21837] Task <794A309F-6F38-4FE6-98BF-957E6D752262>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:11.672360+0800 MaciASL[1753:21853] NSURLConnection finished with error - code -1005
2019-03-09 10:51:11.695273+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C30.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.695417+0800 MaciASL[1753:21834] TIC Read Status [30:0x60000372e100]: 1:54
2019-03-09 10:51:11.696079+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C29.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:11.696179+0800 MaciASL[1753:21834] TIC Read Status [29:0x600003722700]: 1:54
2019-03-09 10:51:12.135154+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C4.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:12.135279+0800 MaciASL[1753:21834] TIC Read Status [4:0x60000370dec0]: 1:54
2019-03-09 10:51:12.389467+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C35.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:12.389604+0800 MaciASL[1753:21834] TIC Read Status [35:0x60000371b300]: 1:54
2019-03-09 10:51:12.390686+0800 MaciASL[1753:21834] Task <18360804-4F45-4CA2-8DFB-E7815EFF2D46>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:12.390891+0800 MaciASL[1753:21837] NSURLConnection finished with error - code -1005
2019-03-09 10:51:12.408223+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C27.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:12.408671+0800 MaciASL[1753:21834] TIC Read Status [27:0x6000037292c0]: 1:54
2019-03-09 10:51:12.689777+0800 MaciASL[1753:21891] [] nw_socket_handle_socket_event [C36.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:12.689906+0800 MaciASL[1753:21891] TIC Read Status [36:0x6000037149c0]: 1:54
2019-03-09 10:51:12.691223+0800 MaciASL[1753:21891] Task <A907391D-1310-4FFF-BF8D-97CA814B5AB2>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:12.692172+0800 MaciASL[1753:21837] NSURLConnection finished with error - code -1005
2019-03-09 10:51:12.782028+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C37.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:12.782163+0800 MaciASL[1753:21834] TIC Read Status [37:0x6000037355c0]: 1:54
2019-03-09 10:51:12.783247+0800 MaciASL[1753:21834] Task <245A2FC5-7ADB-4556-B96F-E79180394119>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:12.783482+0800 MaciASL[1753:21891] NSURLConnection finished with error - code -1005
2019-03-09 10:51:13.083657+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C34.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.083935+0800 MaciASL[1753:21834] TIC Read Status [34:0x60000372f480]: 1:54
2019-03-09 10:51:13.084909+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C38.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.085077+0800 MaciASL[1753:21834] TIC Read Status [38:0x600003738900]: 1:54
2019-03-09 10:51:13.085922+0800 MaciASL[1753:21834] Task <54FDAA75-7F33-4CD1-B702-FC2A7F465895>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:13.086015+0800 MaciASL[1753:21891] NSURLConnection finished with error - code -1005
2019-03-09 10:51:13.086140+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C32.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.086243+0800 MaciASL[1753:21834] TIC Read Status [32:0x60000372d800]: 1:54
2019-03-09 10:51:13.087152+0800 MaciASL[1753:21834] Task <D534E40D-A611-425B-973F-9FB22AE023B4>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:13.087252+0800 MaciASL[1753:21887] NSURLConnection finished with error - code -1005
2019-03-09 10:51:13.131724+0800 MaciASL[1753:21834] [] nw_socket_handle_socket_event [C39.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.131902+0800 MaciASL[1753:21834] TIC Read Status [39:0x600003730b40]: 1:54
2019-03-09 10:51:13.132855+0800 MaciASL[1753:21834] Task <7557CD11-92D5-4E2B-A8D6-9DC030FE0D2A>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:13.133051+0800 MaciASL[1753:21853] NSURLConnection finished with error - code -1005
2019-03-09 10:51:13.467402+0800 MaciASL[1753:21853] [] nw_socket_handle_socket_event [C42.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.467603+0800 MaciASL[1753:21853] TIC Read Status [42:0x600003712c40]: 1:54
2019-03-09 10:51:13.468281+0800 MaciASL[1753:21853] Task <FB8741C2-B13E-4883-A415-9D58491C9827>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:13.468378+0800 MaciASL[1753:21834] NSURLConnection finished with error - code -1005
2019-03-09 10:51:13.486333+0800 MaciASL[1753:21853] [] nw_socket_handle_socket_event [C41.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:13.486487+0800 MaciASL[1753:21853] TIC Read Status [41:0x600003738840]: 1:54
2019-03-09 10:51:13.487251+0800 MaciASL[1753:21853] Task <5C3CF9A8-5850-41F6-8DDA-C891A3034F71>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:13.487338+0800 MaciASL[1753:21891] NSURLConnection finished with error - code -1005
2019-03-09 10:51:14.483533+0800 MaciASL[1753:21890] [] nw_socket_handle_socket_event [C40.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:14.483697+0800 MaciASL[1753:21890] TIC Read Status [40:0x600003738900]: 1:54
2019-03-09 10:51:14.818108+0800 MaciASL[1753:21886] [] nw_socket_handle_socket_event [C43.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:14.818256+0800 MaciASL[1753:21886] TIC Read Status [43:0x6000037309c0]: 1:54
2019-03-09 10:51:14.819120+0800 MaciASL[1753:21886] Task <E2FC576E-EEC9-4286-BF2A-671E6531D91F>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:14.819217+0800 MaciASL[1753:21891] NSURLConnection finished with error - code -1005
2019-03-09 10:51:15.570334+0800 MaciASL[1753:21886] [] nw_socket_handle_socket_event [C25.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:15.570520+0800 MaciASL[1753:21886] TIC Read Status [25:0x60000372ab80]: 1:54
2019-03-09 10:51:15.940329+0800 MaciASL[1753:21867] [] nw_socket_handle_socket_event [C44.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:15.940611+0800 MaciASL[1753:21867] TIC Read Status [44:0x600003739080]: 1:54
2019-03-09 10:51:15.941607+0800 MaciASL[1753:21867] Task <0D0F2149-D7EC-4FCA-A57F-6E36A3AE1C37>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:15.941808+0800 MaciASL[1753:21891] NSURLConnection finished with error - code -1005
2019-03-09 10:51:18.786377+0800 MaciASL[1753:21804] -[__NSCFConstantString background]: unrecognized selector sent to instance 0x1000548f0
2019-03-09 10:51:18.786575+0800 MaciASL[1753:21804] -[__NSCFConstantString background]: unrecognized selector sent to instance 0x1000548f0
2019-03-09 10:51:19.357110+0800 MaciASL[1753:21887] [] nw_socket_handle_socket_event [C33.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:19.357256+0800 MaciASL[1753:21887] TIC Read Status [33:0x6000037215c0]: 1:54
2019-03-09 10:51:19.663477+0800 MaciASL[1753:21867] [] nw_socket_handle_socket_event [C45.1:2] Socket SO_ERROR [54: Connection reset by peer]
2019-03-09 10:51:19.663627+0800 MaciASL[1753:21867] TIC Read Status [45:0x60000373a700]: 1:54
2019-03-09 10:51:19.664319+0800 MaciASL[1753:21867] Task <FBEDFC7C-6782-468E-A894-08429240C82C>.<0> HTTP load failed (error code: -1005 [4:-4])
2019-03-09 10:51:19.664509+0800 MaciASL[1753:21887] NSURLConnection finished with error - code -1005

**Comment by PMheart** [comment]
我这里似乎无法复现此问题。不过根据提供的 log 来看，似乎是网络连线出现异常。

**Comment by btwise** [comment]
也不是网络问题，我下载编译好的1.53版本也是运行只出现菜单，无法显示主窗口，但我运行rehabman的版本或者编译他的版本，运行就正常，应该是代码问题，似乎无法在10.4.4以上版本兼容，是否可以修改一下，或者指定我如何找到问题所在@PMheart

**Comment by btwise** [comment]
@PMheart我的xcode版本是10.1,代码里的一些方法似乎已被新版xcode所抛弃，建议修改一下

**Comment by williambj1** [comment]
据我所知，这个应该不是Xcode的问题，Rehabman的版本更老，用的是10.10的SDK。
目前，本Repo的版本在 OSX 10.7，macOS 10.13，macOS 10.14.3上均运行正常，不知道是不是您的个人设备原因。

**Comment by btwise** [comment]
我知道RM的版本老，所以才想用这个，但是无论如何，还是不能运行，反而RM老版本能正常运行，我的系统是10.14.4 beta，不知道是否有关系@PMheart

**Comment by williambj1** [comment]
非常抱歉，目前我手上没有beta版本的系统，您有能力在正式版本上测试吗？

**Comment by btwise** [comment]
@PMheart
可以测试，thx

**Pull request merged**
