### PR TITLE
[WIP] Added rename syntax for devices in ACPI 

### PR DESCRIPTION
**Pull request by dreamwhite**
The following PR added:

- How to rename correctly a device using only MaciASL patches

### CODE REVIEW

**Comment by vit9696** [comment]
I am not happy with the formatting, please do it properly.

1. Use `<OLD_NAME>/<NEW_NAME>` notation as it is in the rest of the text.
2. There are 4 spaces before the subsequent lines in a list, and code sections are on new lines:

    ```
    3. In order to rename a device via ACPI use the following template:
        ```
        into device label $OLD_NAME set_label begin $NEW_NAME end;
        ```
    ```

Also, if you plan to change more, I could add merge it at once.

**Comment by dreamwhite** [comment]
Oh okay, sorry. Didn't noticed about proper notation. Will push another pull request with more things, so you can merge it at once :)

**Comment by vit9696** [comment]
Cannot you just continue committing to this one and just let me know when we can merge it? I think it will work best!

**Comment by dreamwhite** [comment]
> Cannot you just continue committing to this one and just let me know when we can merge it? I think it will work best!

Of course! No prob :)

**Pull request closed without merging**
