### PR TITLE
Add Chinese(Simplified) Localization zh-Hans

### PR DESCRIPTION
**Pull request by williambj1**
Hi Acidanthera, Moorre, vit9696,

This is a Localization for Chinese(Simplified). 
However, if you don't want to have any Chinese existing in this program, you can close this PR. It's ok for me to store this in my repo.

I'll also be very glad if this is merged, China also has a big demand in hackintoshing.

Thank you very much!

### CODE REVIEW

**Comment by vit9696** [comment]
Thanks! I do not have any issue with it.

@PMheart, I do not speak Chinese, could you please check it out and merge if it looks about ok?

**Comment by PMheart** [comment]
Hi,

I have slightly improved certain aspects. Please take a look: https://github.com/PMheart/MaciASL/commit/844b7e9f08f788b0f886ec3a930a83e0958ee633

Thanks!

**Comment by williambj1** [comment]
Sorry, it seems that we made some changes at the same time. 
I checked 844b7e9 and I found that the mistakes I discovered were already corrected.
So far, 844b7e9 is the correct version. 

Thanks a lot @PMheart @vit9696.

**Comment by williambj1** [comment]
image

I'm quite confused with this part, are there any better translations for this part?

**Comment by vit9696** [comment]
This looks like standard Edit menu you could normally find in any standard app like TextEdit. Also, latest fixes got reverted.

**Comment by williambj1** [comment]
I will check in Microsoft Word to find whether there is a standard term for these words.
@vit9696 Please don't merge right now. I fixed the conflict by using a PR.

**Comment by williambj1** [comment]
@PMheart May you check whether there is any mistakes or not again? 
@vit9696 If there are no mistakes, it'll finally be able to merge. 😊

**Comment by PMheart** [comment]
It seems fine now. Merged.

**Pull request merged**
